<!DOCTYPE html>
    <html lang="en">
    <head>
        <?php include_once 'includes/head.phtml'; ?>
    </head>
    <body>
        <?php include_once 'includes/izbornik.phtml'; ?>
        
        <div class="container" id="program" 
            <?php if(App::dev()): ?>
            	style="background-color: red;"
            <?php endif; ?>>
            <?php echo $sadrzaj; ?>
        </div>

        <?php include_once 'includes/podnozje.phtml'; ?>
        <?php include_once 'includes/skripta.phtml'; ?>
    </body>
</html>
