<!DOCTYPE html>
    <html lang="en">
    <head>
        <?php include_once 'includes\head.phtml'; ?>
    </head>
    <body>
        <?php include_once 'includes\izbornik.phtml'; ?> 
        <div class="container" id="program">
            <?php echo $sadrzaj; ?>
        </div>

        <?php include_once 'includes\podnozje.phtml'; ?>
        <?php include_once 'includes\skripta.phtml'; ?>
    </body>
</html>