
<div class="d-flex justify-content-center" style="margin: 50px 0px 50px 0px;">
<img src="\public\img\wLogo.png" class="img-fluid">
</div>
  
<form class="loginForm" method="post" 
  action="<?=App::config('url');?>prijava/autorizacija">
    <h4 class="text-center">Enter Login Data</h4>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" name="email" class="form-control"  placeholder="example@gmail.com" value="proba@gmail.com<?=$email?>">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" name="password" class="form-control"  placeholder="**********" value="edunova">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
    <?=$poruka?>
</form>