
<?php if(!App::auth()): ?> 

<?php else: ?>
  
  <nav class="navbar fixed-top navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <img src="\public\img\wLogoSmall.png" class="img-fluid" style="margin-right: 10px;">
      <a class="navbar-brand" href="#"><?=App::config('nazivApp');?></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<?=App::config('url');?>pacijent/index">Patients</a>
          </li> 
              <a class="nav-link" href="<?=App::config('url');?>koncentratorKisika/index">Oxygen Concentrator</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Actions</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="<?=App::config('url')?>prikup/index">Collection</a></li> <!--za koristenje gotovih snippeta ide ctrl + space -->
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<?=App::config('url')?>isporuka/index">Delivery</a></li>
            </ul>
          </li>
          <li>
            <?php if(App::admin()): //ako je auth admin?>
              <a class="nav-link" href="<?=App::config('url');?>djelatnik/index">Workers</a>
            <?php endif; ?> 
          </li>
            <?php if(!App::auth()): //ako nije autoriziran prikazi log in?> 
              <a class="nav-link" href="<?=App::config('url');?>prijava/prijava">Log in</a>
            <?php else: ?>
              <a class="nav-link" href="<?=App::config('url');?>prijava/odjava">Log out
              <?php echo App::djelatnik() ?> </a>
          </li>
          <?php endif; ?> 
        </ul>
      </div>
    </div>
  </nav>

<?php endif; ?> 
