

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="<?=App::config('url');?>index"><?=App::config('nazivApp');?></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" aria-current="page" href="<?=App::config('url');?>index/pacijent">Patients</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <?php if(!App::auth()): //ako nije autoriziran prikazi log in?> 
            <a class="nav-link" href="<?=App::config('url');?>index/prijava">Log in</a>
          <?php else: ?>
            <a class="nav-link" href="<?=App::config('url');?>index/odjava">Log out
            <?php echo App::operater() ?> </a>
        </li>
        <?php endif; ?> 
      </ul>
    </div>
  </div>
</nav>