<footer style="background-color: #212529; color: white; ">
        <div class="footer mt-auto text-center">
            <div class="container mt-5 pt-5 pb-5">
                <div id="fot" class="row align-items-start">
                    <div class="col">
                        WEB Servis: 097/7834030
                            <br>
                            <br>
                        <a href="www.linkedin.com/in/adamvicko" class="text-decoration-none text-reset">LinkedIN: AdamVicko</a>
                            <br>
                            <br>
                        <a href="mailto:vickovic2203@gmail.com" class="text-decoration-none text-reset">E-mail: vickovic2203@gmail.com</a>
                    </div>
                </div>
            </div>
        </div>
</footer>
