
    <a href="<?=APP::config('url')?><?=$entitet?>/promjeni/<?=$p->sifra?>">
        <i class="bi bi-pencil"></i>
    </a>
    <?php if(App::admin()): //ako je auth admin?>
    <a 
        onclick="return confirm('Deleting <?=$p->imeprezime?> on <?=$p->datumPrikupa?> ? ')"
        href="<?=APP::config('url')?><?=$entitet?>/izbrisi/<?=$p->sifra?>">
        <i class="bi bi-trash3" style="color: tomato;"></i>
    </a>
    <?php else: ?>

        <i title="Only Admin can delete <?=$entitet?>" class="bi bi-trash3"  style="color: grey;"></i>

<?php endif; ?> 