
<!--KORISTIM SAMO ZA PRIKUP KORSITIO BI I VISE DA IMAM ISTA POSTAVKE-->
    <a href="<?=APP::config('url')?><?=$entitet?>/promjena/<?=$p->sifra?>">
        <i class="bi bi-pencil"></i>
    </a>
    <?php if(App::admin()): //ako je auth admin?>
    <a 
            <?php if($entitet='prikup'): ?>
                onclick="return confirm('Deleting <?=$p->imeprezime?> on <?=$p->datumPrikupa?> ? ')"
            <?php else: ?>
                onclick="return confirm('Deleting <?=$p->imeprezime?> on <?=$p->datumIsporuke?> ? ')"
            <?php endif; ?>
            href="<?=APP::config('url')?><?=$entitet?>/izbrisi/<?=$p->sifra?>">
        <i class="bi bi-trash3" style="color: tomato;"></i>
    </a>
    <?php else: ?>
        <i title="Only Admin can delete <?=$entitet?>" class="bi bi-trash3"  style="color: grey;"></i>
<?php endif; ?>

