<?php if(App::admin()): //ako je auth admin?>
    <a href="promjeni?id=<?=$p->sifra?>">
        <i class="bi bi-pencil"></i>
    </a>
    <a 
        onclick="return confirm('Deleting Collection <?=$p->imeprezime?> on <?=$p->datumPrikupa?> ? ')"
        href="<?=APP::config('url')?>prikup/izbrisi/<?=$p->sifra?>">
        <i class="bi bi-trash3" style="color: tomato;"></i>
    </a>
    <?php else: ?>
    <a 
        href="promjeni?id=<?=$p->sifra?>">
        <i class="bi bi-pencil"></i>
    </a>
    <a href="promjeni?id=<?=$p->sifra?>">
        <i class="bi bi-trash3" style="color: grey;"></i>
    </a>
<?php endif; ?> 