
    <h1>Patients</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New patient</a>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Name and Surname</th>
                <th scope="col">Phone</th>
                <th scope="col">Birth Date</th>
                <th scope="col">Adress</th>
                <th scope="col">OIB</th>
                <th scope="col">Patient Comment</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->imeprezime?></td>
                    <td><?=$p->telefon?></td>
                    <td><?=$p->datumRodenja?></td>
                    <td><?=$p->adresa?></td>
                    <td><?=$p->oib?></td>
                    <td><?=$p->pacijentKomentar?></td>
                    <td>
                        <a href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="izbrisi?id=<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
