
    <h1>Patients</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New patient</a>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Name and Surname</th>
                <th scope="col">Phone</th>
                <th scope="col">Birth Date</th>
                <th scope="col">Adress</th>
                <th scope="col">OIB</th>
                <th scope="col">Patient Comment</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->imeprezime?></td>
                    <td><?=$p->telefon?></td>
                    <td><?=$p->datumRodenja?></td>
                    <td><?=$p->adresa?></td>
                    <td><?=$p->oib?></td>
                    <td>
                        <div class="form-floating">
                            <textarea class="form-control" id="floatingTextarea"><?=$p->pacijentKomentar?></textarea>
                        </div>
                    </td>
                    <td>
                        <a href="<?=APP::config('url')?>pacijent/promjena/<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <?php if(($p->isporucen>0) && ($p->prikupljen>0)): //boze me sacuvaj kako dode do ovog podatka ovdejbez da sam mu ga igdje poslo ili deklariro(samo u read ucito)?>
                        <a 
                            onclick="return confirm('Deleting Patient <?=$p->imeprezime?> ? ')"
                            href="<?=APP::config('url')?>pacijent/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                        <?php elseif(($p->isporucen==0) && ($p->prikupljen==0)): ?>
                        <a 
                            onclick="return confirm('Deleting Patient <?=$p->imeprezime?> ? ')"
                            href="<?=APP::config('url')?>pacijent/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                        <?php else: ?>
                            <i title="OC is not collected from patient!" class="bi bi-trash3" style="color: grey;"></i>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
