
    <h1>Oxygen Concentrator's</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New Oxygen Concentrator</a>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Serial number</th>
                <th scope="col">Working hour's</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Comment</th>
                <th scope="col">Date of Buying</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->serijskiKod?></td>
                    <td><?=$p->radniSat?></td>
                    <td><?=$p->proizvodac?></td>
                    <td><?=$p->model?></td>
                    <td><?=$p->ocKomentar?></td>
                    <td><?=$p->datumKupovine?></td>
                    <td>
                        <a href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="izbrisi?id=<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
