
    <h1>Oxygen Concentrator's</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New Oxygen Concentrator</a>
    <?=$poruka?>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Serial number</th>
                <th scope="col">Working hour's</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Comment</th>
                <th scope="col">Date of Buying</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->serijskiKod?></td>
                    <td><?=$p->radniSat?></td>
                    <td><?=$p->proizvodac?></td>
                    <td><?=$p->model?></td>
                    <td>
                        <div class="form-floating">
                            <textarea class="form-control" id="floatingTextarea"><?=$p->ocKomentar?></textarea>
                        </div>
                    </td>
                    <td><?=$p->datumKupovine?></td>
                    <td>
                        <a href="<?=APP::config('url')?>koncentratorKisika/promjena/<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <?php if(($p->isporucen>0) && ($p->prikupljen>0)): //boze me sacuvaj kako dode do ovog podatka ovdej bez da sam mu ga igdje poslo ili deklariro(samo u read ucito)?>
                        <a 
                            onclick="return confirm('Deleting Oxygen Concentrator <?=$p->serijskiKod?> and all data about it(Collection and Deliveries) ? ')"
                            href="<?=APP::config('url')?>koncentratorKisika/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                        <?php elseif(($p->isporucen==0) && ($p->prikupljen==0)): //boze me sacuvaj kako dode do ovog podatka ovdej bez da sam mu ga igdje poslo ili deklariro(samo u read ucito)?>
                        <a 
                            onclick="return confirm('Deleting Oxygen Concentrator <?=$p->serijskiKod?> and all data about it(Collection and Deliveries) ? ')"
                            href="<?=APP::config('url')?>koncentratorKisika/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                        <?php else: ?>
                            <i title="OC is not collected from patient!" class="bi bi-trash3" style="color: grey;"></i>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
