
<fieldset class="border p-2">
  <legend class="float-none w-auto"><h1>New Collection</h1></legend>
    <form class="row g-3" id="registrationForm" action="<?php echo App::config('url') ?>prikup/noviPrikup" method="post"><?//dovest ce me na promjenu sa svim podacima + sa sifrom?>
        <div class="d-grid col">
            <div class="col-md-11">

                <label for="datumPrikupa">Delivery date</label>
                <input type="date" name="datumPrikupa" id="datumPrikupa">
                
            </div>
            <div class="row" style="margin-top: 50px;">
                <div class="d-grid col-md-6" id="prikupp">
                    <select name="pacijent" id="pacijent">
                    <?php foreach($pacijenti as $p)
                        { ?>
                            <?php if($p->isporucen != $p->prikupljen){ ?>
                                <option value="<?php echo $p->sifra?>"><?php echo $p->imeprezime?></option>
                            <?php }?>

                            <?php 
                        } ?>
                            

                    </select>
                </div>
                <div class="d-grid col-md-6" id="prikupk">
                <select name="koncentratoriKisika" id="koncentratoriKisika">
                    <?php foreach($koncentratoriKisika as $k)
                        { ?>
                            <?php if($k->isporucen != $k->prikupljen ){ ?>
                                  <option value="<?php echo $k->sifra?>"><?php echo $k->serijskiKod?></option>
                            <?php }?>

                            <?php 
                        } ?>
                            

                    </select>

                
                </div>
            </div>

        </div>
        <hr>
            <div class="row" style="margin-top: 50px;">
                <div class="d-grid col">
                    <button type="submit" class="btn btn-success" 
                            value="submit">Submit</button>
                </div>
                <div class="d-grid col">
                    <a href="<?=App::config('url')?>prikup/odustani"
                        class="btn btn-danger">Cancel</a>
                </div>
            </div>
    </form>
</fieldset>

