
    <h1>Collection's</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New collection</a>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Patient</th>
                <th scope="col">Oxygen Concentrator</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->datumPrikupa?></td>
                    <td><?=$p->imeprezime?></td>
                    <td><?=$p->serijskiKod?></td>
                    <td>
                    <?php if(App::admin()): //ako je auth admin?>
                        <a href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a 
                            onclick="return confirm('Deleting Collection <?=$p->imeprezime?> on <?=$p->datumPrikupa?> ? ')"
                            href="<?=APP::config('url')?>prikup/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                        <?php else: ?>
                        <a 
                            href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: grey;"></i>
                        </a>
                    <?php endif; ?> 

                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
