<div class="customModal" style="margin-top: 50px;">
    
    <form class="row g-3" id="registrationForm" action="" method="post">
        <div class="col-md-6">
            <label for="datumPrikupa" class="form-label">Date of Collection</label>
            <input type="text" class="form-control" id="datumPrikupa" 
                name="datumPrikupa" value="<?=$e->datumPrikupa?>">

        </div>
        <div class="col-md-6">
            <label for="serijskikod" class="form-label">OC serial number</label>
            <input type="text" class="form-control" id="serijskikod" 
                name="serijskikod" value="<?=$e->serijskikod?>">
        </div>
        <div class="col-md-6">
            <label for="imeprezime" class="form-label">Patient Name and Surname</label>
            <input type="text" class="form-control" id="imeprezime" 
                name="imeprezime" value="<?=$e->imeprezime?>">
        </div>
        <div class="col-md-6">
            <label for="radnisat" class="form-label">OC working hours</label>
            <input type="text" class="form-control" id="radnisat" 
                name="radnisat" value="<?=$e->radnisat?>">
        </div>
        <div class="col-md-6">
            <label for="adresa" class="form-label">Address</label>
            <input type="text" class="form-control" id="adresa" 
                name="adresa" value="<?=$e->adresa?>">
        </div>
        <div class="col-md-6">
            <label for="komentar" class="form-label">OC comment</label>
            <input type="text" class="form-control" id="komentar" 
                name="komentar" value="<?=$e->komentar?>">
        </div>
        <div class="col-md-6">
            <label for="telefon" class="form-label">Telephone</label>
            <input type="text" class="form-control" id="telefon" 
                name="telefon" value="<?=$e->telefon?>">
        </div>
        <hr>
        <?=$poruka?>
        <div class="row" style="margin-top: 50px;">
            <div class="d-grid col">
                <button type="submit" class="btn btn-success" 
                value="dodaj">Create</button>
            </div>
            <div class="d-grid col">
                <a href="<?=App::config('url')?>prikup/index"
                    class="btn btn-danger">Cancle</a>
            </div>
        </div>
        
    </form>

</div>