
<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name and Surname</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Role</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $i=1; foreach($podaci as $p): ?>
                <tr>
                    <th><?=$i?><?php $i++;?></th>
                    <td><?=$p->imeprezime?></td>
                    <td><?=$p->email?></td>
                    <td><?=$p->telefon?></td>
                    <td><?=$p->uloga?></td>
                    <td>
                        <a href="promjeni?id=<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="izbrisi?id=<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
