
<h1 style="margin: 0 0 50px 0;" >Search all data</h1>

    <form action="" method="get">
        <input type="text" id="uvjet" placeholder=" Search all" 
            value="<?=$uvjet?>">
    </form>

    <table class="table table-dark table-hover" style="margin: 20px 0 20px 0;">
        <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->vrsta?></td>
                    <td><?=$p->tekst?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>