
<fieldset class="border p-2">
  <legend class="float-none w-auto"><h1>Delivery</h1></legend>
    <form class="row g-3" id="registrationForm" action="<?php echo App::config('url') ?>isporuka/promjena/<?=$e->sifra?>" method="post"><?//dovest ce me na promjenu sa svim podacima + sa sifrom?>
        <div class="d-grid col">
            <div class="col-md-11">

                <label for="datumIsporuke">Delivery date</label>
                <input type="date" name="datumIsporuke" id="datumIsporuke"
                    value="<?=$e->datumIsporuke?>">
                
            </div>
            <div class="row" style="margin-top: 50px;">
                <div class="d-grid col">

                    <?php include_once 'popisPacijenata.phtml' ?>
        
                </div>
                <div class="d-grid col">

                <?php include_once 'popisKoncentratoraKisika.phtml' ?>
                
                </div>
            </div>

        </div>
        <hr>
          <?=$poruka?>
            <div class="row" style="margin-top: 50px;">
                <div class="d-grid col">
                    <button type="submit" class="btn btn-success" 
                            value="Submit">Submit</button>
                </div>
                <div class="d-grid col">
                    <a href="<?=App::config('url')?>isporuka/odustani/<?=$e->sifra?>"
                        class="btn btn-danger">Cancel</a>
                </div>
            </div>
    </form>
</fieldset>

