
<h1>Deliveries</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="<?=App::config('url')?>isporuka/novi" class="btn btn-primary">New delivery</a>
</div>

<div class="table-responsive">
    <table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Patient</th>
                <th scope="col">Oxygen Concentrator</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($podaci as $p): ?>
                <tr>
                    <td><?=$p->datumIsporuke?></td>
                    <td>
                    <a href="<?=App::config('url')?>isporuka/promjena/<?=$p->sifra?>"><i class="bi bi-pencil"></i></a>    
                    <?php if(App::admin()): //ako je auth admin?>
                            <a
                                onclick="return confirm('Deleting <?=$p->imeprezime?> on <?=$p->datumIsporuke?> ? ')"
                                href="<?=APP::config('url')?>isporuka/izbrisi/<?=$p->sifra?>"
                            >
                                <i class="bi bi-trash3" style="color: tomato;"></i>
                            </a>
                    <?php else: ?>
                        <i title="Only Admin can delete delivery" class="bi bi-trash3"  style="color: grey;"></i>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
