<div class="popisKoncentratoraKisika">
    <input type="text" id="uvjetKisik" placeholder="Oxygen search">    
    <div style="min-height: 20px;">
        <div style="font-size: 0.6rem;" id="poruka"></div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Oxygen Concentrator </th>
                <th>Akcija</th>
            </tr>
        </thead>
        <tbody id="podaciKisik">
            <?php foreach($e->koncentratorKisika as $p): ?>
            <tr>
                <td>
                    <?=$p->serijskiKod//pazi da ti je i za pacijent?> 
                </td>
                <td>
                    <a href="#" class="odabraniKoncentratorKisika" id="p_<?=$p->sifra?>">
                    <i class="bi bi-trash3"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        </table>
</div>