<div class="isporukaKoncentratorKisika">
    <input type="text" id="uvjetKisik" placeholder="Oxygen search">    
    <div style="min-height: 20px;">
        <div style="font-size: 0.6rem;" id="poruka"></div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Oxygen Concentrator </th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody id="podaciKisik">

            <tr>
                <td>
                    <?=$e->serijskiKod//pazi da ti je i za pacijent?> 
                </td>
                <td>
                    <a href="#" class="odabraniKoncentratorKisika" id="p_<?=$e->sifra?>">
                    <i class="bi bi-trash3"></i>
                    </a>
                </td>
            </tr>

        </tbody>
        </table>
</div>