<div class="popisPacijenata">
    <input type="text" id="uvjet" placeholder="Patient search">    
    <div style="min-height: 20px;">
        <div style="font-size: 0.6rem;" id="poruka"></div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Patient </th>
                <th>Akcija</th>
            </tr>
        </thead>
        <tbody id="podaci">
            <?php foreach($e->pacijenti as $p): ?>
            <tr>
                <td>
                    <?=$p->pacijent?>
                </td>
                <td>
                    <a href="#" class="odabraniPacijent" id="p_<?=$p->sifra?>">
                    <i class="bi bi-trash3"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        </table>
</div>