<div class="customModal" style="margin-top: 50px;">

    <div class="text-center" style="margin: 100px 0 0 0;">
        <h1>Modification Collection Date</h1>
    </div>

    <form class="row g-3" id="" action="" method="post">
        <div class="col-md-6">
            <label for="datumKupovine" class="form-label">Date of buying</label>
            <input type="text" class="form-control" id="datumPrikupa" 
                name="datumPrikupa" value="<?=$e->datumPrikupa?>">
        </div>

        <div class="row" style="margin-top: 50px;">
            <div class="d-grid col">
                <button type="submit" class="btn btn-success" 
                value="promjena">Modify</button>
            </div>
            <div class="d-grid col">
                <a href="<?=App::config('url')?>prikup/index"
                    class="btn btn-danger">Cancel</a> 
            </div>
        </div>
        
    </form>

</div>