
<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
  <a href="novi" class="btn btn-primary">New worker</a>
</div>
<table class="table table-dark table-hover" style="margin: 50px 0 50px 0;">
    
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Ime i Prezime</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Role</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php $i=1; foreach($podaci as $p): ?>
            <tr>
                <th><?=$i?><?php $i++;?></th>
                <td><?=$p->imeprezime?></td>
                <td><?=$p->email?></td>
                <td><?=$p->telefon?></td>
                <td><?=$p->uloga?></td>
                <td>
                    <a href="promjeni?id=<?=$p->sifra?>">Change</a>
                </td>
            </tr>
        <?php endforeach; ?>
       
  </tbody>
</table>