
<h1>Workers</h1>

<div class="d-grid gap-2 col-6 mx-auto" style="margin: 50px 0 0 0;">
    <a href="novi" class="btn btn-primary">New worker</a>
    <?=$poruka?>
</div>

<div class="table-responsive" style="margin: 50px 0 0px 0;">
    <form action="" method="get">
        <input type="text" name="uvjet"
        placeholder="Part of Name" value="<?=$uvjet?>" >
    </form>
    <?php include 'stranicenje.phtml' ?>
    <table class="table table-dark table-hover" style="margin: 20px 0 20px 0;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name and Surname</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Role</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $i=1; foreach($podaci as $p): ?>
                <tr>
                    <th><?=$i?><?php $i++;?></th>
                    <td><?=$p->imeprezime?></td>
                    <td><?=$p->email?></td>
                    <td><?=$p->telefon?></td>
                    <td><?=$p->uloga?></td>
                    <td>
                        <a href="<?=APP::config('url')?>djelatnik/promjena/<?=$p->sifra?>">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a 
                            onclick="return confirm('Deleting Worker <?=$p->imeprezime?> and all data about it ? ')"
                            href="<?=APP::config('url')?>djelatnik/izbrisi/<?=$p->sifra?>">
                            <i class="bi bi-trash3" style="color: tomato;"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php include 'stranicenje.phtml' ?>